/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Restaurant, MenuItem } from "./types";

const RAW_INITIAL_RESTAURANTS: Restaurant[] = [
  // 1. 小木屋 (Cabin)
  {
    restaurant_id: 1,
    name: "小木屋鬆餅 中央大學店",
    category: "點心",
    walking_distance: 1,
    rating: 4.6,
    popularity: 92,
    avg_price: 65,
    is_open: true,
    is_group_friendly: true,
    has_ac: false,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "校內大草坪旁",
    signature_dishes: ["巧克力香蕉鬆餅", "紐奧良烤雞鬆餅", "紅茶拿鐵"],
  },
  // 2. 松果 (Pines)
  {
    restaurant_id: 11,
    name: "松果餐廳",
    category: "台式",
    walking_distance: 2,
    rating: 4.1,
    popularity: 81,
    avg_price: 90,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "松平樓 1 樓",
    signature_dishes: ["自選精緻自助餐", "招牌炸排骨飯", "慢火香燉排骨蘇湯"],
  },
  // 3. 松苑 (Pine Court)
  {
    restaurant_id: 12,
    name: "LALA Kitchen 新美式餐廳(中大店)",
    category: "美式",
    walking_distance: 2,
    rating: 4.4,
    popularity: 88,
    avg_price: 250,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "松苑 1 樓",
    signature_dishes: ["紐奧良香脆烤雞翅", "美式厚牛經典培根漢堡", "手作香烤披薩"],
  },
  {
    restaurant_id: 40,
    name: "漢堡王 Burger King 中央店",
    category: "美式",
    walking_distance: 2,
    rating: 4.2,
    popularity: 85,
    avg_price: 130,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "松苑 1 樓",
    signature_dishes: ["經典火烤牛肉華堡", "薯條可樂特惠餐", "雙起司安格斯漢堡"],
  },
  {
    restaurant_id: 15,
    name: "玖蔦家火山丼 - 中大店",
    category: "日式",
    walking_distance: 2,
    rating: 4.3,
    popularity: 84,
    avg_price: 140,
    is_open: true,
    is_group_friendly: false,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "松苑九村食堂",
    signature_dishes: ["火山招牌牛肉丼飯", "黃金豬排咖哩蓋飯", "炙燒鮭魚丼飯"],
  },
  {
    restaurant_id: 14,
    name: "Louisa Coffee 路易莎咖啡(中央大學門市)",
    category: "飲料",
    walking_distance: 2,
    rating: 4.2,
    popularity: 89,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "松苑 2 樓",
    signature_dishes: ["經典熱拿鐵咖啡", "小茶點熱壓吐司", "特選莊園美式"],
  },
  {
    restaurant_id: 41,
    name: "全家便利商店 中壢中央三店",
    category: "點心",
    walking_distance: 2,
    rating: 4.5,
    popularity: 95,
    avg_price: 50,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "松苑一樓",
    signature_dishes: ["夯番薯", "全家Fami霜淇淋", "全家經典熱拿鐵"],
  },
  // 4. 宵夜街 (Midnight Street)
  {
    restaurant_id: 22,
    name: "滿食記燒肉丼飯",
    category: "日式",
    walking_distance: 4,
    rating: 4.3,
    popularity: 90,
    avg_price: 130,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街中段路口",
    signature_dishes: ["招牌鮮嫩日式醬味牛肉丼", "香濃極厚起司豬排丼飯", "特製泡菜梅花豬肉蓋飯"],
  },
  {
    restaurant_id: 17,
    name: "來客",
    category: "台式",
    walking_distance: 3,
    rating: 4.1,
    popularity: 82,
    avg_price: 110,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街前路段",
    signature_dishes: ["宮保雞丁香炒蓋飯", "鐵板黑椒牛肉套餐", "香煎醬爆炸醬豆腐飯"],
  },
  {
    restaurant_id: 42,
    name: "田家牛肉麵",
    category: "麵食",
    walking_distance: 4,
    rating: 4.3,
    popularity: 84,
    avg_price: 130,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["精燉紅燒川味牛肉麵", "香蒜老滷大腸拌麵", "古早味餛飩湯麵"],
  },
  {
    restaurant_id: 34,
    name: "緣杏 廣東粥飯麵館 中央店",
    category: "台式",
    walking_distance: 4,
    rating: 4.0,
    popularity: 83,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街口旁",
    signature_dishes: ["香滑小火生滾皮蛋瘦肉粥", "鮮美廣東大骨海鮮稀飯", "XO老醬火爆港式生撈麵"],
  },
  {
    restaurant_id: 29,
    name: "香煎小鋪",
    category: "台式",
    walking_distance: 4,
    rating: 4.2,
    popularity: 85,
    avg_price: 140,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街美食中段",
    signature_dishes: ["金脆九層塔香煎雞腿排套餐", "鮮美鐵板沙茶牛柳飯", "日式鹽烤鯖魚精緻飯"],
  },
  {
    restaurant_id: 43,
    name: "25食堂",
    category: "台式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 79,
    avg_price: 90,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["家常風味雞肉便當", "酥炸黃金排骨簡餐", "清炒吻仔魚雙拼盒飯"],
  },
  {
    restaurant_id: 18,
    name: "楊滇風 南洋料理",
    category: "南洋",
    walking_distance: 4,
    rating: 4.3,
    popularity: 86,
    avg_price: 145,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街巷內熱點",
    signature_dishes: ["南洋手調香椰黃咖哩雞腿飯", "泰味辣酸鮮蝦大撈麵", "叻沙海陸雙拼烏龍麵"],
  },
  {
    restaurant_id: 44,
    name: "喜樂廚房",
    category: "台式",
    walking_distance: 4,
    rating: 4.2,
    popularity: 80,
    avg_price: 95,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["蜜汁香烤大雞腿便當", "椒鹽嫩烤豬里肌套餐", "黑胡椒香爆牛五花"],
  },
  {
    restaurant_id: 45,
    name: "咖哩老師",
    category: "日式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 81,
    avg_price: 110,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["老師傅脆皮起司豬排咖哩飯", "溫燉黑松露唐揚雞咖哩", "黃金熔岩起司可樂餅咖哩"],
  },
  {
    restaurant_id: 46,
    name: "瑞麟美而美",
    category: "早餐",
    walking_distance: 3,
    rating: 4.0,
    popularity: 87,
    avg_price: 65,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["台式脆皮起司肉排蛋餅", "鐵板蘑菇肉醬麵套餐", "大甲芋頭沙鮮奶茶"],
  },
  {
    restaurant_id: 36,
    name: "傻師傅湯包",
    category: "點心",
    walking_distance: 4,
    rating: 4.2,
    popularity: 88,
    avg_price: 75,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街中段路口",
    signature_dishes: ["經典手工爆肉汁小鮮肉湯包", "鮮蝦蟹黃爆汁小湯包", "老火香菇煨大雞湯鍋"],
  },
  {
    restaurant_id: 8,
    name: "厚臉皮粉漿蛋餅",
    category: "宵夜",
    walking_distance: 4,
    rating: 4.8,
    popularity: 98,
    avg_price: 55,
    is_open: true,
    is_group_friendly: false,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街中段路口",
    signature_dishes: ["爆漿起司黑豬肉粉漿厚蛋餅", "老墨肉醬香辣重口味蛋餅", "鮮熬招牌黑糖厚奶"],
  },
  {
    restaurant_id: 3,
    name: "香城燒臘小館",
    category: "港式",
    walking_distance: 4,
    rating: 4.4,
    popularity: 95,
    avg_price: 110,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街前段",
    signature_dishes: ["老火明爐香燒大三寶飯", "極香爆汁脆皮五花燒肉飯", "蔥油脆烤手撕雞腿飯"],
  },
  {
    restaurant_id: 47,
    name: "東東生鮮手工大水餃",
    category: "麵食",
    walking_distance: 4,
    rating: 4.2,
    popularity: 81,
    avg_price: 80,
    is_open: true,
    is_group_friendly: false,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["手工生鮮高麗菜鮮肉水餃 (10顆)", "招牌韭菜干貝水晶大水餃", "經典鮮美酸辣湯"],
  },
  {
    restaurant_id: 48,
    name: "來來炒飯燴飯",
    category: "台式",
    walking_distance: 4,
    rating: 4.3,
    popularity: 85,
    avg_price: 90,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["大火香爆臘肉肉絲炒飯", "黑胡椒紐西蘭沙朗牛柳燴飯", "經典黃金櫻花蝦蛋炒飯"],
  },
  {
    restaurant_id: 49,
    name: "粥王",
    category: "台式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 82,
    avg_price: 80,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["綿密大骨干貝生滾皮蛋粥", "精製滑雞百合營養粥", "川燙鮮透抽魚皮海鮮粥"],
  },
  {
    restaurant_id: 50,
    name: "388飯麵食堂",
    category: "台式",
    walking_distance: 4,
    rating: 4.0,
    popularity: 78,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["古早味祕製滷肉飯套餐", "極品鮮甜乾汁蚵仔大撈麵", "香蒜紅燒獅子頭精緻飯"],
  },
  {
    restaurant_id: 51,
    name: "惡魔爆漿炸彈",
    category: "宵夜",
    walking_distance: 4,
    rating: 4.4,
    popularity: 89,
    avg_price: 70,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["招牌流沙蔥香爆漿炸彈蔥油餅", "雙重起司惡魔爆汁雞排", "香脆黃金小熱狗拼盤"],
  },
  {
    restaurant_id: 52,
    name: "廣東腸粉",
    category: "港式",
    walking_distance: 4,
    rating: 4.3,
    popularity: 82,
    avg_price: 80,
    is_open: true,
    is_group_friendly: false,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["極致嫩滑港式蜜汁叉燒蛋腸粉", "海鮮鮮蝦雙蛋絲綢大腸粉", "養生大骨高湯煲仔湯"],
  },
  {
    restaurant_id: 53,
    name: "宵夜屋自助餐",
    category: "台式",
    walking_distance: 4,
    rating: 3.9,
    popularity: 87,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["秤重自選盒飯餐", "脆皮炸雞大雞腿", "秘釀紅燒豬腳"],
  },
  {
    restaurant_id: 54,
    name: "翔食堂",
    category: "台式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 80,
    avg_price: 90,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["極致日式厚切黃金咔滋豬排丼", "嫩烤香甜蒜苗五花腩便當", "麻婆豆腐雙拼燴飯"],
  },
  {
    restaurant_id: 55,
    name: "麥味登-中壢宵夜街店",
    category: "早餐",
    walking_distance: 3,
    rating: 4.2,
    popularity: 89,
    avg_price: 80,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街中段路口",
    signature_dishes: ["超厚手打美式牛肉培根堡", "幸福法式吐司精緻里肌盤", "經典黃金脆薯可樂提神套組"],
  },
  {
    restaurant_id: 56,
    name: "一品鍋",
    category: "鍋物",
    walking_distance: 4,
    rating: 4.2,
    popularity: 86,
    avg_price: 130,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["大腸臭臭白菜香鍋", "起司香濃鮮乳牛奶牛肉鍋", "極品重口味川東麻辣豬肉鍋"],
  },
  {
    restaurant_id: 57,
    name: "小惡魔茶飲(Pretty Devil)",
    category: "飲料",
    walking_distance: 3,
    rating: 4.4,
    popularity: 88,
    avg_price: 55,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["惡魔雙倍波霸皇家珍奶", "招牌香椰拿鐵水果冰茶", "經典微糖英式皇家紅茶"],
  },
  {
    restaurant_id: 58,
    name: "霸王香雞排",
    category: "宵夜",
    walking_distance: 4,
    rating: 4.3,
    popularity: 91,
    avg_price: 90,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["霸王特大寸斷脆皮多汁大雞排", "秘製甘梅酥脆地瓜條", "黃金大魷魚洋蔥酥拼盤"],
  },
  {
    restaurant_id: 59,
    name: "比大爺健康蔬果滷味-中央店",
    category: "宵夜",
    walking_distance: 4,
    rating: 4.1,
    popularity: 85,
    avg_price: 80,
    is_open: true,
    is_group_friendly: false,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["招牌香醇蔬果中藥滷大臉盆", "精緻手夾鮮嫩鴨血脆腸乾拌組", "大推科學麵高麗菜香爆滷味"],
  },
  {
    restaurant_id: 60,
    name: "立橙茶飲",
    category: "飲料",
    walking_distance: 3,
    rating: 4.2,
    popularity: 80,
    avg_price: 50,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["香橙百香手工爆爆極鮮綠茶", "立橙特條燕麥香濃厚鮮奶", "金桔檸檬薄荷爽口茶"],
  },
  {
    restaurant_id: 61,
    name: "夏克堤",
    category: "飲料",
    walking_distance: 3,
    rating: 4.1,
    popularity: 79,
    avg_price: 45,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["傳統炭焙鐵觀音四季青厚奶", "夏克堤香草蜂蜜燕麥奶", "手作薄荷檸檬多多冰沙"],
  },
  {
    restaurant_id: 62,
    name: "茶繪",
    category: "飲料",
    walking_distance: 3,
    rating: 4.3,
    popularity: 82,
    avg_price: 55,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "宵夜街",
    signature_dishes: ["手打鮮芝士荔枝奶蓋蜜香紅茶", "原葉碳焙大紅袍拿鐵", "香甜四季春寒天凍凍茶"],
  },

  // 5. 後門 (Back Gate)
  {
    restaurant_id: 21,
    name: "阿米玲食堂-日式豬排專賣-",
    category: "日式",
    walking_distance: 3,
    rating: 4.7,
    popularity: 91,
    avg_price: 150,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口",
    signature_dishes: ["厚切腰內日式黃金卡滋豬排飯", "經典黃金里肌起司瀑布豬排蓋飯", "日式咖哩雞唐揚揚出炸雞套餐"],
  },
  {
    restaurant_id: 63,
    name: "馬爾波 Marbo / 義大利麵 / 手工 Pizza",
    category: "義式",
    walking_distance: 4,
    rating: 4.5,
    popularity: 87,
    avg_price: 180,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路",
    signature_dishes: ["松露野菇炙燒燻嫩雞義大利麵", "黃金熔岩起司夏威夷拉絲手工披薩", "拿坡里茄汁嫩煎牛柳大撈意麵"],
  },
  {
    restaurant_id: 64,
    name: "巧味香早餐店",
    category: "早餐",
    walking_distance: 3,
    rating: 4.1,
    popularity: 80,
    avg_price: 60,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口主街側巷",
    signature_dishes: ["經典培根玉米脆香起司蛋餅", "手作美式厚牛里肌三明治", "古早味古法調製冰紅茶"],
  },
  {
    restaurant_id: 27,
    name: "Sidewalk人行道蔬食",
    category: "素食",
    walking_distance: 4,
    rating: 4.2,
    popularity: 82,
    avg_price: 160,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門中央路商圈街區",
    signature_dishes: ["頂級牛肝菌黑松露奶油野菇麵", "經典瑪格麗特起司薄脆餅", "香濃波希米亞極致奶油野菇燉飯"],
  },
  {
    restaurant_id: 65,
    name: "哈堡堡輕食早午餐中大直營店",
    category: "早餐",
    walking_distance: 4,
    rating: 4.3,
    popularity: 88,
    avg_price: 90,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路街區",
    signature_dishes: ["樂活無負擔輕食嫩胸雞肉拼盤", "德式法蘭克福起司煙燻歐姆巨蛋", "香脆黃金薯薯起司壓吐司"],
  },
  {
    restaurant_id: 19,
    name: "No.17 White House",
    category: "義式",
    walking_distance: 4,
    rating: 4.4,
    popularity: 89,
    avg_price: 170,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路精緻美食道",
    signature_dishes: ["招牌奶油青醬炙嫩雞胸義大利麵", "義大利辣味培根奶油白醬燉飯", "法式金磚奶油香烤吐司糖"],
  },
  {
    restaurant_id: 66,
    name: "迷路義麵屋",
    category: "義式",
    walking_distance: 4,
    rating: 4.2,
    popularity: 83,
    avg_price: 155,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口",
    signature_dishes: ["香濃奶油南瓜泥黃金蛤蠣麵", "經典蒜香黑胡椒煙燻培根麵", "主廚特製白醬香烤嫩鮮透抽飯"],
  },
  {
    restaurant_id: 20,
    name: "大嗑中央大學(蔬菜蛋餅專專賣店)",
    category: "早餐",
    walking_distance: 3,
    rating: 4.6,
    popularity: 90,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路口巷弄",
    signature_dishes: ["頂級大嗑手作蔬菜熔岩起司歐姆蛋捲餐", "香辣黑豬肉排脆口粉漿蛋餅", "手打美式重磅熔岩芝心黑漢堡"],
  },
  {
    restaurant_id: 67,
    name: "花路꽃길石鍋拌飯專賣",
    category: "韓式",
    walking_distance: 4,
    rating: 4.3,
    popularity: 85,
    avg_price: 135,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["經典韓式爆起司辣炒年糕石鍋拌飯", "春川辣炒肥牛石燒鍋巴拌飯", "經典釜山海鮮起司厚煎餅"],
  },
  {
    restaurant_id: 68,
    name: "白鬍子牛排 中央大學店",
    category: "美式",
    walking_distance: 4,
    rating: 4.3,
    popularity: 92,
    avg_price: 160,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路商街中心",
    signature_dishes: ["頂級特厚黑胡椒沙朗嫩肩牛排餐", "極致黃金脆皮雙拼無骨大雞腿排", "白鬍子特製香蒜大蒜厚抹吐司自取"],
  },
  {
    restaurant_id: 69,
    name: "八哥重慶酸辣粉 中央大學店",
    category: "麵食",
    walking_distance: 4,
    rating: 4.4,
    popularity: 93,
    avg_price: 100,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路旁",
    signature_dishes: ["頂級正宗重慶麻辣肥腸酸辣紅薯粉", "香濃酸香招牌口水雞大撈麵", "老成都特色大瓷碗麻辣抄手"],
  },
  {
    restaurant_id: 70,
    name: "萊姆斯早午餐",
    category: "早餐",
    walking_distance: 4,
    rating: 4.1,
    popularity: 82,
    avg_price: 95,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["皇家經典班尼迪克蛋英式早午餐盤", "萊姆斯手作酥炸魚排芝麻漢堡", "手作厚切奶油丹麥香烤麵包組"],
  },
  {
    restaurant_id: 71,
    name: "惟客美而美",
    category: "早餐",
    walking_distance: 3,
    rating: 4.0,
    popularity: 80,
    avg_price: 60,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口街區",
    signature_dishes: ["古早味祕醬蘑菇鐵板炒麵", "台式培根起司蛋餅", "手調古早味香濃冰奶茶"],
  },
  {
    restaurant_id: 72,
    name: "Daddy's美式餐廳",
    category: "美式",
    walking_distance: 5,
    rating: 4.4,
    popularity: 85,
    avg_price: 190,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["重磅美式煙燻培根熔岩花生漢堡", "美式厚切椒鹽黃金脆薯條", "Daddy自家秘釀特調香炸雞翅"],
  },
  {
    restaurant_id: 38,
    name: "香米便當‧自助餐",
    category: "台式",
    walking_distance: 4,
    rating: 3.1,
    popularity: 70,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路街口",
    signature_dishes: ["自選秤重家常雙拼中式盒飯", "酥香黑胡椒咔滋大雞排飯", "阿嬤手釀家傳爌肉便當"],
  },
  {
    restaurant_id: 73,
    name: "達啵廚房 Double 2 Kitchen",
    category: "美式",
    walking_distance: 5,
    rating: 4.3,
    popularity: 84,
    avg_price: 180,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路巷弄",
    signature_dishes: ["美式酥脆巨型塔安格斯雙牛堡", "達啵特調微酸塔塔鱈魚大炸包", "鮮炸洋蔥圈拼盤餐"],
  },
  {
    restaurant_id: 23,
    name: "家香美食屋",
    category: "台式",
    walking_distance: 3,
    rating: 4.0,
    popularity: 81,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門商圈旁",
    signature_dishes: ["川香重慶老底子紅燒排骨暖麵", "手剪古早味蒜泥大滷肉飯", "新鮮大骨老鴨香筍羹"],
  },
  {
    restaurant_id: 74,
    name: "歐姆萊斯",
    category: "台式",
    walking_distance: 4,
    rating: 4.2,
    popularity: 82,
    avg_price: 110,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["日式金黃瀑布歐姆滑蛋熟咖哩雞", "招牌鮮潤番茄肉醬牛肉歐姆蛋飯", "頂級黑椒鱈魚香酥排蛋包"],
  },
  {
    restaurant_id: 75,
    name: "樂活堡 - 中央店",
    category: "早餐",
    walking_distance: 4,
    rating: 4.1,
    popularity: 83,
    avg_price: 75,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口",
    signature_dishes: ["樂活輕卡無負擔厚切土司", "美式經典起司培根吉事堡", "特熬現磨香濃研磨黑咖啡"],
  },
  {
    restaurant_id: 76,
    name: "尚臻鍋燒食堂",
    category: "台式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 83,
    avg_price: 120,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門中央路商圈旁",
    signature_dishes: ["招牌香辣極緻川味原骨小火鍋(附冬粉)", "東北正宗家鄉酸菜白肉砂銅小鍋", "老火燉補黑麻油鮮雞高湯鍋"],
  },
  {
    restaurant_id: 77,
    name: "麥克小姐",
    category: "早餐",
    walking_distance: 4,
    rating: 4.0,
    popularity: 81,
    avg_price: 75,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["英式皇家大餐精選起司培根拼盤", "麥克手作蒜片卡滋香雞美式漢堡", "經典香甜蜜糖烤吐司片"],
  },
  {
    restaurant_id: 39,
    name: "新福（紅油抄手）",
    category: "麵食",
    walking_distance: 4,
    rating: 3.7,
    popularity: 79,
    avg_price: 80,
    is_open: true,
    is_group_friendly: false,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門中央路內巷",
    signature_dishes: ["古早味鮮手工紅油辣椒大抄手", "川香紅油手工手拉牛肉麵🍜", "招牌香辣芝麻肉絲乾拉麵"],
  },
  {
    restaurant_id: 78,
    name: "萊客堡早餐",
    category: "早餐",
    walking_distance: 3,
    rating: 4.0,
    popularity: 78,
    avg_price: 65,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["招牌咔拉脆香雞皮起司大蛋餅", "手作美式厚牛蔬菜壓三明治", "古早味香醇鮮奶紅茶冰"],
  },
  {
    restaurant_id: 79,
    name: "大中央厚切牛排",
    category: "美式",
    walking_distance: 4,
    rating: 4.2,
    popularity: 86,
    avg_price: 170,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口",
    signature_dishes: ["大中央招牌厚切黑胡椒沙朗牛排餐", "極致咔滋脆皮椒鹽鐵板香腿排餐", "主廚特製鮮茄牛肉番茄意麵", "酥皮濃湯與汽水無限熱食自用桌"],
  },
  {
    restaurant_id: 80,
    name: "廚窗 Kitchen Bliss",
    category: "美式",
    walking_distance: 5,
    rating: 4.5,
    popularity: 89,
    avg_price: 220,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門中央路巷內",
    signature_dishes: ["頂級紐奧良蜜汁香烤舒肥嫩雞拼盤", "經典法式熔岩起司松露烘歐姆蛋捲餐", "特釀伯爵蜜橙冰茶"],
  },
  {
    restaurant_id: 81,
    name: "太極飯糰",
    category: "早餐",
    walking_distance: 3,
    rating: 4.3,
    popularity: 88,
    avg_price: 55,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路旁",
    signature_dishes: ["招牌太極雙拼黑糙米紫米古法飯糰", "重口味辣菜脯老油條脆口大飯糰", "濃郁無糖黑豆漿"],
  },
  {
    restaurant_id: 82,
    name: "麥堡堡早點",
    category: "早餐",
    walking_distance: 3,
    rating: 4.1,
    popularity: 80,
    avg_price: 60,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["台式極香黑胡椒鐵板麵套餐", "咔拉雞起司特大美式黑漢堡", "老火提神錫蘭冰紅茶"],
  },
  {
    restaurant_id: 83,
    name: "108果汁",
    category: "飲料",
    walking_distance: 3,
    rating: 4.4,
    popularity: 85,
    avg_price: 60,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口",
    signature_dishes: ["現榨極香百香檸檬四季青特調", "慢磨紅蘿蔔蘋果綜合高能果汁", "招牌香甜木瓜鮮燉牛奶高杯"],
  },
  {
    restaurant_id: 84,
    name: "街角216",
    category: "台式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 79,
    avg_price: 90,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門口",
    signature_dishes: ["招牌厚片卡滋起司手工炸里肌豬排飯", "極鮮黑椒牛里肌香火爆炒便當", "自熬黃金竹筍排骨湯組"],
  },
  {
    restaurant_id: 28,
    name: "竹香快餐",
    category: "台式",
    walking_distance: 5,
    rating: 4.2,
    popularity: 95,
    avg_price: 95,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "後門武興路段",
    signature_dishes: ["香脆黃金招牌大炸雞腿便當", "超嫩手切蒜泥五花白豬肉飯盒", "秘釀古法黑胡椒牛柳大便當"],
  },
  {
    restaurant_id: 85,
    name: "Backdoor Café",
    category: "飲料",
    walking_distance: 4,
    rating: 4.5,
    popularity: 86,
    avg_price: 120,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路街口巷弄",
    signature_dishes: ["手工烘焙精品莊園手沖咖啡黑美式", "鮮奶油提拉米蘇蛋糕手作輕甜點", "宇治濃宇治抹茶香濃鮮奶拿鐵"],
  },
  {
    restaurant_id: 86,
    name: "八方雲集-中壢中央店",
    category: "台式",
    walking_distance: 4,
    rating: 4.2,
    popularity: 90,
    avg_price: 85,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門中央路口",
    signature_dishes: ["經典金脆招牌生煎鍋貼 (10顆)", "手工生鮮高麗菜鮮肉大水餃", "正宗重慶酸辣大碗粉與酸辣湯"],
  },
  {
    restaurant_id: 87,
    name: "巷口咖啡",
    category: "飲料",
    walking_distance: 3,
    rating: 4.2,
    popularity: 78,
    avg_price: 80,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門側巷口",
    signature_dishes: ["巷口經典特製醇拿鐵咖啡餐", "極香水果四季熱泡冰果茶", "小點烤脆皮厚片培根吐司"],
  },
  {
    restaurant_id: 88,
    name: "食間",
    category: "台式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 80,
    avg_price: 90,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門",
    signature_dishes: ["古早味招牌蒜香爌肉大拌麵", "手作厚切咔滋豬里肌排飯餐", "黃金大甲芋頭軟骨羹湯"],
  },
  {
    restaurant_id: 26,
    name: "雙饗丼-桃園中央店",
    category: "日式",
    walking_distance: 4,
    rating: 4.1,
    popularity: 84,
    avg_price: 120,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路中段生輝街",
    signature_dishes: ["招牌極厚雙拼岩漿起司大丼飯", "經典黃金卡滋豬排厚切咖哩飯", "特製日式川汁泡菜牛五花蓋飯"],
  },
  {
    restaurant_id: 89,
    name: "健康鹽水雞",
    category: "台式",
    walking_distance: 3,
    rating: 4.2,
    popularity: 83,
    avg_price: 80,
    is_open: true,
    is_group_friendly: false,
    has_ac: false,
    has_seats: false,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "後門宵夜街口熱點底段",
    signature_dishes: ["招牌去骨鮮嫩大雞腿特大拼盤", "鮮綠高麗菜脆椒筍片生鮮時蔬組", "自調中藥香椒麻鹽香拌油包"],
  },
  {
    restaurant_id: 90,
    name: "福泉豆花",
    category: "點心",
    walking_distance: 4,
    rating: 4.5,
    popularity: 89,
    avg_price: 50,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: true,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門五興路街",
    signature_dishes: ["經典白鬍子香醇黑糖起司奶蓋布丁豆花", "招牌鮮潤三色芋圓花生豆花冰", "自製甘甜清香嫩仙草凍凍大杯"],
  },
  {
    restaurant_id: 91,
    name: "滿分小舖（Straight A）",
    category: "早餐",
    walking_distance: 4,
    rating: 4.1,
    popularity: 82,
    avg_price: 70,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "後門武興路",
    signature_dishes: ["香脆極大椒鹽咔拉腿大漢堡", "培根熔岩花生手工抓餅", "慢磨自調提神冰豆牛奶紅茶"],
  },

  // 6. 前門 (Front Gate)
  {
    restaurant_id: 31,
    name: "友竹居茶藝館",
    category: "台式",
    walking_distance: 8,
    rating: 4.0,
    popularity: 78,
    avg_price: 350,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: false,
    img_url: "",
    location_desc: "雙連坡中央路前門口周邊",
    signature_dishes: ["傳統養生花雕溫雞火鍋套餐", "珍饌老饕清蒸海鮮大鮮鱸魚", "頂級凍頂烏龍茶點點炸燒盤"],
  },

  // 7. 麥當勞 (McDonald's)
  {
    restaurant_id: 92,
    name: "麥當勞-平鎮民族餐廳－設有得來速",
    category: "美式",
    walking_distance: 12,
    rating: 4.5,
    popularity: 96,
    avg_price: 140,
    is_open: true,
    is_group_friendly: true,
    has_ac: true,
    has_seats: true,
    is_vegetarian: false,
    has_takeout: true,
    is_midnight_snack: true,
    img_url: "",
    location_desc: "民族路三段外圍商圈",
    signature_dishes: ["經典大麥克牛肉雙層堡特大套餐", "香脆多汁黃金麥鴨塊套餐 (10入)", "勁辣咔啦香酥大雞翅盒飯"],
  }
];

export const normalizeCategory = (name: string, category: string, isVeg?: boolean, isSnack?: boolean): string => {
  const norm = (category || "").trim();
  if (norm === "素食" || norm === "蔬食.素食" || isVeg) return "蔬食.素食";
  if (name.includes("小木屋鬆餅") || name.includes("Shine Mood") || name.includes("鬆餅") || name.includes("大腸包小腸") || name.includes("湯包") || name.includes("茶藝館") || name.includes("點心") || norm === "點心" || name.includes("豆花")) return "點心";
  if (name.includes("咖啡廳") || name.includes("咖啡社") || name.includes("飲料") || norm === "飲料" || name.includes("咖啡")) return "飲料";
  if (name.includes("老香黑麻油") || name.includes("火鍋") || name.includes("小火鍋") || name.includes("燉食堂") || name.includes("砂鍋") || norm === "鍋物" || name.includes("一品鍋")) return "鍋物";
  if (name.includes("蛋餅") || name.includes("宵夜") || isSnack || norm === "宵夜" || name.includes("炸彈")) return "宵夜";
  if (name.includes("蔬菜蛋餐") || name.includes("早餐") || name.includes("早午餐") || norm === "早餐" || name.includes("美而美") || name.includes("小舖")) return "早餐";
  if (name.includes("合菜") || name.includes("燉肉") || name.includes("丼饭") || name.includes("丼飯") || name.includes("便當") || name.includes("排骨") || name.includes("燒臘") || name.includes("飯") || name.includes("自助") || name.includes("歐媽") || norm === "飯" || norm === "港式" || norm === "韓式") return "飯";
  if (name.includes("麵") || name.includes("拉麵") || name.includes("撈麵") || name.includes("義大利麵") || name.includes("抄手") || norm === "麵食" || name.includes("粉")) return "麵食";
  if (name.includes("LALA") || norm === "晚餐") return "晚餐";
  if (norm === "午餐") return "午餐";
  return "飯"; // fallback
};

export const INITIAL_RESTAURANTS: Restaurant[] = RAW_INITIAL_RESTAURANTS.map(r => ({
  ...r,
  category: normalizeCategory(r.name, r.category, r.is_vegetarian, r.is_midnight_snack)
}));

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Restaurant 1: 小木屋鬆餅
  {
    menu_id: 101,
    restaurant_id: 1,
    item_name: "巧克力香蕉鬆餅",
    price: 65,
    spicy_level: "無辣",
    popularity_score: 9.5,
    tags: ["店內熱門", "甜點推薦"],
    ingredients: ["香蕉", "巧克力醬", "牛奶面糊"],
    size_desc: "一般大份",
    rating: 4.7
  },
  {
    menu_id: 102,
    restaurant_id: 1,
    item_name: "紐奧良烤雞鬆餅",
    price: 75,
    spicy_level: "微辣",
    popularity_score: 8.8,
    tags: ["今日限定"],
    ingredients: ["雞肉", "生菜", "紐奧良特製醬汁"],
    size_desc: "一般大份",
    rating: 4.5
  },
  // Restaurant 11: 松果餐廳
  {
    menu_id: 1101,
    restaurant_id: 11,
    item_name: "自選精緻自助餐",
    price: 90,
    spicy_level: "無辣",
    popularity_score: 8.0,
    tags: ["CP首選"],
    ingredients: ["時令蔬菜", "大肉片", "香白米飯"],
    size_desc: "招牌餐盒",
    rating: 4.0
  },
  // Restaurant 12: LALA Kitchen
  {
    menu_id: 1201,
    restaurant_id: 12,
    item_name: "美式紐奧良香烤雞翅",
    price: 155,
    spicy_level: "微辣",
    popularity_score: 9.2,
    tags: ["開胃強推"],
    ingredients: ["去骨雞翼", "特調美式酸辣醬"],
    size_desc: "一盤裝",
    rating: 4.6
  },
  // Restaurant 21: 阿米玲食堂
  {
    menu_id: 2101,
    restaurant_id: 21,
    item_name: "厚切腰內日式黃金豬排飯",
    price: 150,
    spicy_level: "無辣",
    popularity_score: 9.6,
    tags: ["主廚推薦", "金牌招牌"],
    ingredients: ["厚切腰內肉", "日本進口炸粉", "熟熟高麗菜絲"],
    size_desc: "超飽足拼盤定食",
    rating: 4.8
  },
  // Restaurant 22: 滿食記燒肉丼飯
  {
    menu_id: 2201,
    restaurant_id: 22,
    item_name: "招牌鮮嫩日式醬味牛肉丼",
    price: 130,
    spicy_level: "無辣",
    popularity_score: 9.3,
    tags: ["店長推薦", "人氣熱搜"],
    ingredients: ["特級牛五花肉", "慢火熬製和風醬油汁", "大青蔥"],
    size_desc: "特大一碗裝",
    rating: 4.7
  },
  // Restaurant 28: 竹香快餐
  {
    menu_id: 2801,
    restaurant_id: 28,
    item_name: "香脆黃金招牌大炸雞腿便當",
    price: 95,
    spicy_level: "無辣",
    popularity_score: 9.5,
    tags: ["校園風雲爆量"],
    ingredients: ["精選溫體大後腿肉", "秘製裹漿", "三樣大配菜"],
    size_desc: "便當盒防漏款",
    rating: 4.7
  }
];
